import { Lang } from "@/src/@types/ai-options/lang";

export default function languageString(lang: Lang): string {
  const languageMap: Record<Lang, string> = {
    fr: "French",
    en: "English",
    de: "German",
    it: "Italian",
    es: "Spanish",
    pt: "Portuguese",
    ru: "Russian",
    sv: "Swedish",
    tr: "Turkish",
    zh: "Chinese",
    ja: "Japanese",
    ko: "Korean",
    id: "Indonesian",
    hi: "Hindi",
    ar: "Arabic",
    cs: "Czech",
    da: "Danish",
    fi: "Finnish",
    he: "Hebrew",
    hu: "Hungarian",
    ms: "Malay",
    nl: "Dutch",
    no: "Norwegian",
    pl: "Polish",
    ro: "Romanian",
    th: "Thai",
    uk: "Ukrainian",
    vi: "Vietnamese",
    el: "Greek",
    bg: "Bulgarian",
    fa: "Persian",
    sk: "Slovak",
    sl: "Slovenian",
    sr: "Serbian",
    tl: "Tagalog",
    hr: "Croatian",
    ca: "Catalan",
    et: "Estonian",
    lt: "Lithuanian",
    lv: "Latvian",
    sw: "Swahili",
    cy: "Welsh",
    af: "Afrikaans",
  };

  return languageMap[lang] || "Unknown Language";
}

export const languageList = {
  fr: { name: "French", flag: "🇫🇷" },
  en: { name: "English", flag: "🇬🇧" },
  de: { name: "German", flag: "🇩🇪" },
  it: { name: "Italian", flag: "🇮🇹" },
  es: { name: "Spanish", flag: "🇪🇸" },
  pt: { name: "Portuguese", flag: "🇵🇹" },
  ru: { name: "Russian", flag: "🇷🇺" },
  sv: { name: "Swedish", flag: "🇸🇪" },
  tr: { name: "Turkish", flag: "🇹🇷" },
  zh: { name: "Chinese", flag: "🇨🇳" },
  ja: { name: "Japanese", flag: "🇯🇵" },
  ko: { name: "Korean", flag: "🇰🇷" },
  id: { name: "Indonesian", flag: "🇮🇩" },
  hi: { name: "Hindi", flag: "🇮🇳" },
  ar: { name: "Arabic", flag: "🇦🇪" },
  cs: { name: "Czech", flag: "🇨🇿" },
  da: { name: "Danish", flag: "🇩🇰" },
  fi: { name: "Finnish", flag: "🇫🇮" },
  he: { name: "Hebrew", flag: "🇮🇱" },
  hu: { name: "Hungarian", flag: "🇭🇺" },
  ms: { name: "Malay", flag: "🇲🇾" },
  nl: { name: "Dutch", flag: "🇳🇱" },
  no: { name: "Norwegian", flag: "🇳🇴" },
  pl: { name: "Polish", flag: "🇵🇱" },
  ro: { name: "Romanian", flag: "🇷🇴" },
  th: { name: "Thai", flag: "🇹🇭" },
  uk: { name: "Ukrainian", flag: "🇺🇦" },
  vi: { name: "Vietnamese", flag: "🇻🇳" },
  el: { name: "Greek", flag: "🇬🇷" },
  bg: { name: "Bulgarian", flag: "🇧🇬" },
  fa: { name: "Persian", flag: "🇮🇷" },
  sk: { name: "Slovak", flag: "🇸🇰" },
  sl: { name: "Slovenian", flag: "🇸🇮" },
  sr: { name: "Serbian", flag: "🇷🇸" },
  tl: { name: "Tagalog", flag: "🇵🇭" },
  hr: { name: "Croatian", flag: "🇭🇷" },
  ca: { name: "Catalan", flag: "🇪🇸" },
  et: { name: "Estonian", flag: "🇪🇪" },
  lt: { name: "Lithuanian", flag: "🇱🇹" },
  lv: { name: "Latvian", flag: "🇱🇻" },
  sw: { name: "Swahili", flag: "🇹🇿" },
  cy: { name: "Welsh", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
  af: { name: "Afrikaans", flag: "🇿🇦" },
};
