export type Lang =
  | "fr" // French
  | "en" // English
  | "de" // German
  | "it" // Italian
  | "es" // Spanish
  | "pt" // Portuguese
  | "ru" // Russian
  | "sv" // Swedish
  | "tr" // Turkish
  | "zh" // Chinese
  | "ja" // Japanese
  | "ko" // Korean
  | "id" // Indonesian
  | "hi" // Hindi
  | "ar" // Arabic
  | "cs" // Czech
  | "da" // Danish
  | "fi" // Finnish
  | "he" // Hebrew
  | "hu" // Hungarian
  | "ms" // Malay
  | "nl" // Dutch
  | "no" // Norwegian
  | "pl" // Polish
  | "ro" // Romanian
  | "th" // Thai
  | "uk" // Ukrainian
  | "vi" // Vietnamese
  | "el" // Greek
  | "bg" // Bulgarian
  | "fa" // Persian
  | "sk" // Slovak
  | "sl" // Slovenian
  | "sr" // Serbian
  | "tl" // Tagalog
  | "hr" // Croatian
  | "ca" // Catalan
  | "et" // Estonian
  | "lt" // Lithuanian
  | "lv" // Latvian
  | "sw" // Swahili
  | "cy" // Welsh
  | "af"; // Afrikaans
