export type personalities =
  | "provocative"
  | "deep"
  | "charismatic"
  | "compassionate"
  | "sarcastic"
  | "wise"
  | "creative"
  | "nurturing"
  | "adventurous"
  | "meticulous"
  | "gentle"
  | "quirky"
  | "stoic"
  | "visionary"
  | "tactical"
  

export type personalitiesValues =
    | "Provocative Professor"
    | "Deep Thinker"
    | "Charismatic Leader"
    | "Compassionate Mentor"
    | "Sarcastic Comedian"
    | "Wise Sage"
    | "Creative Innovator"
    | "Nurturing Coach"
    | "Adventurous Explorer"
    | "Meticulous Analyst"
    | "Gentle Guide"
    | "Quirky Enthusiast"
    | "Stoic Philosopher"
    | "Visionary Dreamer"
    | "Tactical Strategist"

