import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import "react-toastify/dist/ReactToastify.css";
import Provider from "@/context/Provider";
import { ThemeProvider } from "@/src/theme/ThemeProvider";
import { clsx } from "clsx";
import NextTopLoader from "nextjs-toploader";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Session } from "next-auth";
import dynamic from "next/dynamic";
import { Navbar } from "@/src/feature/Navbar";
const inter = Inter({ subsets: ["latin"] });
import { Bitter, Caveat, Nunito } from "next/font/google";

const sans = Nunito({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
});
const serif = Bitter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-serif",
});
const display = Caveat({ subsets: ["latin"], variable: "--font-display" });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const ToastProvider = dynamic(() => import("@/src/toastify/ToastProvider"));

export default async function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: Session;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning={true}
      className={`${sans.variable} ${serif.variable}  ${display.variable} font-sans`}>
      <Provider session={session}>
        <body className={inter.className}>
          <ToastProvider>
            <NextTopLoader
              template='<div class="bar" role="bar"><div class="peg"></div></div> 
              <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
              color="#3d3d3d"
              initialPosition={0.08}
              crawlSpeed={200}
              height={2}
              crawl={true}
              showSpinner={true} 
              easing="ease"
              speed={200}
              shadow={false}
            />
          </ToastProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system-ui"
            enableSystem>
            <Navbar />
              <main>
                <div className="container">{children}</div>
              </main>
          </ThemeProvider>
        </body>
      </Provider>
    </html>
  );
}
